### ISSUE TITLE
WSC does not recognize an abbreviation

### ISSUE THREAD

**Issue by Reinmar** [WebSpellChecker/ckeditor-plugin-wsc#23]
1. Type 'U.S. President'.
2. Open WSC.
3. It will try to replace 'U.S' with 'U.S.', what of course leads to two subsequent dots.

Not a recent regression.

**Comment by wsc-julia-shaptala** [comment]
Hello,

Unfortunately, the current spellcheck engine has some limitations and we are not able to fix this problem at the moment. This will be addressed with a new engine.

Sincerely,
