### ISSUE TITLE
GUI not fully initialized when using WSC with keyboard

### ISSUE THREAD

**Issue by mlewand** [WebSpellChecker/ckeditor-plugin-wsc#24]
Tested with FF28@Win7 (branch master git hash:ab7b009995bb7329fd8858226a67812fc54101b3)

In CKEditor you are able to navigate within dialogs only using keyboard. In version 3 this case will
1. open any sample with CKEditor and WSC (i.e. samples/replacebyclass.html)
2. open menu from a toolbar button "Spell Check As You Type"
3. use "Check Spelling" option
4. when WSC will fully load dialog press `alt + F10`
5. press `right arrow` key to moge one tab to right
6. press `enter` to move focus to the tab

**Expected result:**
Dialog should dispatch ajax and load all needed content, just like in case of a tab click.

**Current result:**
Dialog is incomplete, and no extra data is being loaded.

additional info:
1. it seems that it's a regression because when i tested it in http://ckeditor.com/demo it works fine

**Comment by wsc-julia-shaptala** [comment]
Hello,

This is a know issue. At the moment we froze all the work related to enhancements or fixes to low priority issues in WSC as we are working on the new version of this product.

Sincerely,
