### ISSUE TITLE
Is there a plan to support custom domain?

### ISSUE THREAD

**Issue by krisha2** [WebSpellChecker/ckeditor-plugin-wsc#29]
As the comment in the plugin.js source code says, custom domain is not supported.: 
// SpellChecker doesn't work in Opera, with custom domain, IE Compatibility Mode and IE (8 & 9) Quirks Mode

I guess this is really only not supported in IE? Is there any plan to support this, as I see there has been made som fixes for using custom domain in other ckeditor plugins; http://dev.ckeditor.com/ticket/10165. 

Or is there at least possible to enable this for other browsers than IE?

For now we have to remove this plugin from our editor, and we have to consider if we will continue to pay for spellcheck if we only have scayt available.

**Comment by brajo** [comment]
I presume that once this is looked into it will fix any cross-domain security issues?
We provide our CMS through the client's administration panels which all run CKEditor from our company's main domain, but the administration panels are on the client's own domains.

i.e.   www.clientssite.com uses CKEditor from www.ourcompany.com

Looking forward to your reply.
Cheers

**Comment by wsc-julia-shaptala** [comment]
Hello @brajo!

Could you please advise if this problem is still actual for you?

Sincerely,
