### ISSUE TITLE
[IE11] Error thrown when running spellchecking on document with on errors.

### ISSUE THREAD

**Issue by adelura** [WebSpellChecker/ckeditor-plugin-wsc#30]
Browser: IE11.

1. Open editor with user interface language which is diffrent than english. You can use sample `uilanguages` and select some language option from dropdown (I used polish one).
2. Make sure your content is 100% valid (linguistically).
4. Click `Ckeck spelling` button from dropdown.

**Actual result**
There is a error in console.
```
SCRIPT438: Obiekt nie obsługuje właściwości lub metody „toUpperCase”
File: wsc.js, Line: 5, Column: 374
```
Which means that object does not have property or method like `toUpperCase`.

**Comment by WebSpellChecker** [comment]
We're glad to inform you that the fix is committed into master branch.
