### ISSUE TITLE
Cannot read property 'DefaultParams' on wsc-dev 

### ISSUE THREAD

**Issue by gituser7777** [WebSpellChecker/ckeditor-plugin-wsc#31]
I tried to plug the current wsc-dev bundle into ckeditor plugins and getting the error below, when trying to open spell check. 

Uncaught TypeError: Cannot read property 'DefaultParams' of undefinedVM8220:1 (anonymous function)VM8220:1 (anonymous function)VM8220:1 (anonymous function)wsc.js?t=D6IE:432 NS.setIframewsc.js?t=D6IE:469 NS.sendDatawsc.js?t=D6IE:1170 showFirstTabwsc.js?t=D6IE:1865 (anonymous function)

please let me know if this requires additional configuration to work with ckeditor

**Comment by WebSpellChecker** [comment]
Could you please provide your steps to plug the WSC plugin and the version of CKEditor?

**Comment by artiq5** [comment]
@gituser7777 any update on this?

**Comment by wsc-julia-shaptala** [comment]
Hello!

As there are no comments or information that can help us to reproduce the problem, we close this one.

Sincerely,
