### ISSUE TITLE
Ads in WSC dialog are not displayed correctly

### ISSUE THREAD

**Issue by Comandeer** [WebSpellChecker/ckeditor-plugin-wsc#34]
Bug in CKEditor: http://dev.ckeditor.com/ticket/13949
## Steps to reproduce
1. Open CKEditor with WSC plugin (may be http://ckeditor.com/demo).
2. Click "Spell Checker" button and choose "Check spelling" option.
## Expected result

Ads are shown on the top of the dialog.
## Actual result

IE 8 displays "Internet Explorer cannot display the webpage" error instead.
## Other details (browser, OS, CKEditor version, installed plugins)

Internet Explorer 8 on Windows XP

**Comment by jswiderski** [comment]
You can also use this pre-set https://github.com/ckeditor/ckeditor-presets/tree/wsc-test-env-4.5.5

**Comment by Tade0** [comment]
This error is no longer reproducible.

**Comment by WebSpellChecker** [comment]
The issue is confirmed and reported into our internal bugtracking system with low priority.

**Comment by wsc-bug-hunter** [comment]
Cannot reproduce this issue. Ads on the top of the dialog. We have another issue https://github.com/WebSpellChecker/ckeditor-plugin-wsc/issues/45 but this can be closed.
