### ISSUE TITLE
IE10 throw an error when spell checking is started.

### ISSUE THREAD

**Issue by msamsel** [WebSpellChecker/ckeditor-plugin-wsc#40]
Problem detected on VM with Win7 x86, IE10 `10.9200.17609`.

## How to reproduce:
* Open IE10 with CKEditor. I used home page of [ckeditor](http://ckeditor.com/) for testing.
* Open console
* Select "Check spelling"
* Usually in first time plugin is loaded, but now refresh page and repeat previous point
* In my case usually after 3rd refresh plugin doesn't load at all.
* There appear exception:
```
SEC7130: Potential cross-site scripting detected in 'http://loader.webspellchecker.net/spellcheck3//script/ssrv.cgi'. The content has been modified by the XSS Filter.
```

## Screenshot:
![virtualbox_ie10 - win7_23_05_2017_15_37_49](https://cloud.githubusercontent.com/assets/9017322/26356920/f9e09e68-3fcd-11e7-8db9-0e41d2e3cdfa.png)

**Comment by beatadelura** [comment]
Similar problem detected on VM with Win10 x64, IE11 `11.1198.14393.0`

## Steps to reproduce:

1. Open IE11.
2. Go to [ckeditor](http://ckeditor.com/) and clear editor content.
3. Open [wiki page](https://en.wikipedia.org/wiki/Zenobia) in new tab.
4. Copy the first paragraph included information from the right sidebar:

![screen shot 2017-05-23 at 16 04 25](https://cloud.githubusercontent.com/assets/12029308/26358097/c62afaba-3fd1-11e7-87cc-34d7aa0b3779.png)

5. Go back to the tab with CKEditor and paste text from clipboard.
6. Select `Spell checker` --> `Check spelling`

## Unexpected result:

![screen shot 2017-05-23 at 16 10 17](https://cloud.githubusercontent.com/assets/12029308/26358293/5cbcc4d6-3fd2-11e7-85db-452672f5df35.png)

**Comment by wsc-bug-hunter** [comment]
@beatadelura @msamsel Thank you for contacting us! We have managed to reproduce the issue. We will provide more details after technical review (ETA: 24/05/2017)

Regards,

**Comment by wsc-bug-hunter** [comment]
@msamsel @beatadelura Currently the root of issue is still under review. We will notify you when review will be finished.

Regards,

**Comment by rahiemb** [comment]
Has this issue been resolved?

**Comment by wsc-bug-hunter** [comment]
This issue has been fixed.

**Comment by shubhanshujaiswal123** [comment]
I am facing an issue in spell checker.
Can you please help ?
The suggestions are not showing it only shows loading.. there.
It was working fine but for two three days its not working.
![image 1](https://user-images.githubusercontent.com/16736939/51429097-33d3bb00-1c31-11e9-849f-f25e8b8caa84.png)
![image](https://user-images.githubusercontent.com/16736939/51429098-346c5180-1c31-11e9-9756-1bf42c219872.png)
