### ISSUE TITLE
[IE9/IE8] `<!--[if !IE...` comments visible in WSC dialog

### ISSUE THREAD

**Issue by f1ames** [WebSpellChecker/ckeditor-plugin-wsc#45]
A comment is visible in WSC dialog in IE9/IE8 (see screenshot below):

<img width="613" alt="screen shot 2017-08-14 at 11 29 46" src="https://user-images.githubusercontent.com/1061942/29267581-90a1ae30-80e9-11e7-9d68-02c21cbc4032.png">

I think this is some dynamic part (I see iframe there) so it is not really hardcoded inside the plugin, which means it is not directly a plugin issue, but still worth a look.

**Comment by wsc-bug-hunter** [comment]
Hello f1ames,

Thank you so much for heads-up!
We have reproduced this issue and added a task for this.

Regards,
WebSpellChecker

**Comment by wsc-julia-shaptala** [comment]
Hello!

Unfortunately, we have to mark this issue as a know issue which won't be fixed for this version of the product. We are working on the development of the new version of WSC where we address all the issues.
