### ISSUE TITLE
WSC 5.0.1 throws an error in CKEditor 4.10.0

### ISSUE THREAD

**Issue by msamsel** [WebSpellChecker/ckeditor-plugin-wsc#49]
Hi,

I'm testing integration WSC and SCAYT (5.0.1) with CKEditor (4.10.0). During tests I found that WSC throws an error in console of each browser.

Reproduction steps:
1. Take CKEditor4 in current major version.
2. Build package with SCAYT and WSC
3. Enable `SCAYT` (without enabling error does not occur)
4. Open `Check spelling`
5. Press `Finish Checking`

I've used this repository and branch for testing: https://github.com/ckeditor/ckeditor-presets/tree/wsc-test-env-5.0.1

Problem doesn't occur when I used WSC & SCAYT in version 4.9.5. (CKEditor version in both cases remained the same.)

In case of any additional questions feel free to ask. :)

![screen shot 2018-06-15 at 16 34 53](https://user-images.githubusercontent.com/9017322/41474091-5f59aac2-70bb-11e8-9584-18bec36cad1c.png)

**Comment by artem-skolota** [comment]
Hi @msamsel,

I have tried to reproduce the issue with no luck. I have built the standard package and run the sample under IIS on the Windows.

Everything works fine if I follow your steps.

1. Could you please send us the ckeditor folder where you have reproduced the issue? 
2. Could you please tell me if there is any additional step which can help us to reproduce the issue?

Hope to hear from you soon.

Best regards,
Arti

**Comment by msamsel** [comment]
I hope those details will help you track the issue.

Testing environment:
* CKEditor4 major branch ( b4806ceaf )
* SCAYT ( fff19b3 )
* WSC 5.0.1 ( 17d166a )
* About scayt shows hash ( 05a67c4f )
* Browser: 67.0.3396.87 (Official Build) (64-bit)
* System: MacOS 10.13.5

Reproduction steps:
1. Clone repository: https://github.com/ckeditor/ckeditor-presets
2. Checkout to branch: `wsc-test-env-5.0.1`
3. Update and init submodules: `git submodule update --init`
4. Run script in main directory `./build.sh full all`
5. This should create `build` folder with CKEditor4 in previously mentioned version together with SCAYT and WSC plugins
6. Open page `build/4.10.0/full-all/ckeditor/samples/index.html`
7. Enable SCAYT
8. Open spell checking
9. Press finish button

Error appear (with unfold call stack):
```
Uncaught TypeError: d.addWordToUserDictionary is not a function
    at wsc.js?t=I5I7:28
(anonymous) @ wsc.js?t=I5I7:28
setTimeout (async)
settext @ wsc.js?t=I5I7:28
G @ wsc.js?t=I5I7:32
postMessage (async)
_sendCmd @ spell.js:138
FinishChecking @ spell.js:1114
cmd_outer__page @ spell.js:819
handler @ spell.js:1134
postMessage (async)
send @ wsc.js?t=I5I7:7
d @ wsc.js?t=I5I7:47
(anonymous) @ ckeditor.js:527
h @ ckeditor.js:10
(anonymous) @ ckeditor.js:11
click @ ckeditor.js:526
(anonymous) @ ckeditor.js:518
h @ ckeditor.js:10
(anonymous) @ ckeditor.js:11
(anonymous) @ ckeditor.js:61
```

Visualisation of steps 7-9 you can find below in gif.

![jun-18-2018 11-20-18](https://user-images.githubusercontent.com/9017322/41528250-d42d74f2-72e9-11e8-9102-b7231ba9a1c6.gif)

**Comment by artem-skolota** [comment]
Thank you so much!

I am checking it right now.

I will let you know as soon as we get any results.

Regards,

__________________________________________

*Artem Skolota*
QA Engineer | WebSpellChecker LLC
Phone:  +1 (917) 259-1071 <(917)%20259-1071>
Mobile: +3 80 (99) 658-7733

**Comment by msamsel** [comment]
@artem-skolota actually I test it additionally on Windows 7 and it seems that problem doesn't occur on Chrome under Windows. I can only find it on Chrome on MacOS.

**Comment by artem-skolota** [comment]
Cool!

Thank you for the details provided.



__________________________________________

*Artem Skolota*
QA Engineer | WebSpellChecker LLC
Phone:  +1 (917) 259-1071 <(917)%20259-1071>
Mobile: +3 80 (99) 658-7733

**Comment by msamsel** [comment]
I tried to reach the source of the problem, but I couldn't find it. :(
In private mode plugin works perfectly fine. I tried to achieve the same thing be removing plugins from browser (without entering private mode), but even when all plugins was removed error still appear in my case. I have no idea what kind of settings I have, which cause the issue.
From unknown reason this line: https://github.com/WebSpellChecker/ckeditor-plugin-wsc/blob/master/dialogs/wsc.js#L927 throw an Error.
`scaytInstance` seems to be an empty object, but I don't know how it happen, because all the time `editor.scayt` contains proper values.

From my perspective issue might be closed as error is not occur in other environments.

**Comment by shubhanshujaiswal123** [comment]
If I try to see the suggestion of any word then its only giving me loading ..
can you please tell me whats the issue and how it can be fixed ?

![image](https://user-images.githubusercontent.com/16736939/51429171-fd4a7000-1c31-11e9-99a3-5639ec6e8fd5.png)
![image 1](https://user-images.githubusercontent.com/16736939/51429172-fde30680-1c31-11e9-8679-db9721aa7261.png)
