### ISSUE TITLE
SCAYT Plugin stops working

### ISSUE THREAD

**Issue by vhert09** [WebSpellChecker/ckeditor-plugin-wsc#51]
ckscayt.js:40 The defined language code en-us is not available or supported for your customer ID. Please contact us at support@webspellchecker.net or submit a ticket at webspellchecker.net website.

I'm using CKEditor v 4.4.7.

Please let me know how to fix this issue. Thanks

**Comment by wsc-julia-shaptala** [comment]
Hi @vhert09,

The supported language codes for SCAYT plugin for CKEditor is described here: https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-scayt_sLang

'en-us' is not a language code that is supported, the correct is 'en_US'. After this update, make sure you cleaned your browser local storage as the information about the previous setting of the language is saved in the local storage.

Regards,
