### ISSUE TITLE
WSC Dialog windows hangs on 'Finish Checking' action if SCAYT plugin is removed

### ISSUE THREAD

**Issue by artem-abakumov** [WebSpellChecker/ckeditor-plugin-wsc#52]
Steps to reproduce:
1. Open attached sample page with WSC plugin for CKEditor 
2. Click Check Spelling
3. Click Finish Checking

Expected behavior: The dialog window is closed
Actual result: The dialog window hangs

[wsc_2032.zip](https://github.com/WebSpellChecker/ckeditor-plugin-wsc/files/2723533/wsc_2032.zip)

**Comment by mlewand** [comment]
I added a simplified repro case at https://codepen.io/mlewand/pen/dwdNGW

It looks like 5.0.1.3 fixed the issue 👍

**Comment by shubhanshujaiswal123** [comment]
If I try to see the suggestion of any word then its only giving me loading ..
can you please tell me whats the issue and how it can be fixed ?

![image](https://user-images.githubusercontent.com/16736939/51375442-7ed3be00-1acb-11e9-992a-a7a942a85dff.png)
