### ISSUE TITLE
Use CKEDITOR.getUrl when referencing style sheets

### ISSUE THREAD

**Issue by glen-84** [WebSpellChecker/ckeditor-plugin-wsc#55]
`wsc.css` is referenced without using [CKEDITOR.getUrl](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#method-getUrl).

I can send a PR, but it'll probably be a lot faster for you to just make the changes yourself (1 line).

See also:
  * https://github.com/WebSpellChecker/ckeditor-plugin-scayt/issues/166
  * https://github.com/ckeditor/ckeditor-dev/issues/1194

**Comment by wsc-julia-shaptala** [comment]
Hi @glen-84, our team will review this request and get back with the comments as soon as possible.

**Comment by wsc-julia-shaptala** [comment]
@glen-84, please see our comments in the related issue.

- [WebSpellChecker/ckeditor-plugin-scayt#166](https://github.com/WebSpellChecker/ckeditor-plugin-scayt/issues/166)

**Comment by wsc-julia-shaptala** [comment]
@glen-84, we will add this small enhancement as a part of our next release 5.4.0. ETA: end of March, beginning of April 2019.

**Comment by artem-abakumov** [comment]
@glen-84 5.4.0 was released. Enhancement was included.

**Comment by glen-84** [comment]
Thank you! 🙂
