### ISSUE TITLE
Bug found in wsc.js when inside chrome extension

### ISSUE THREAD

**Issue by jarlep** [WebSpellChecker/ckeditor-plugin-wsc#56]
We use webspellchecker in a web application running in a chrome extension, and we noticed we got a ton of errors from Chrome OS reported in trackjs from wsc.js in CKeditor. We have made a Chrome OS app that runs our exam system and then also CKEditor.
Checked latest version 4.11.3 and get the same error there. 

I made a workaround in the minified code by doing

if("string"===typeof a.data &&(a=window.JSON.parse(a.data))&&a.id)
instead of
if((a=window.JSON.parse(a.data))&&a.id)

The reason is that a.data is an object in some events. Look at the screendump (I formatted the source):
![image](https://user-images.githubusercontent.com/15678761/54272490-1a415680-4584-11e9-8759-25c6c948ef84.png)

**Comment by jarlep** [comment]
```
var handlerIncomingData = function(event) {
		event = event || window.event;
		var response;
		try {
			response = window.JSON.parse(event.data);
		} catch (e) {}

		if(response && response.id) {
			handlerId[response.id](response);
		}
	};
```
should fix it

**Comment by wsc-julia-shaptala** [comment]
Hi @jarlep,

We will review the information about your issue and get back to you with our comments shrtly.

Kind regards,

**Comment by wsc-julia-shaptala** [comment]
@jarlep, we will add this small enhancement as a part of our next release 5.4.0. ETA: end of March, beginning of April 2019.
