### ISSUE TITLE
Disable some of the options inside the Scayt dropdown list inside CKEditor 4

### ISSUE THREAD

**Issue by jmonfu** [WebSpellChecker/ckeditor-plugin-wsc#57]
I am using the built in 'Scayt' to spell check the text inside my React application.

toolbar: [
{ name: 'editing', items: ['Find', 'Replace', '-', 'SelectAll', 'Scayt'] },

I have a question, is it possible to remove some of the options for the dropdown list it comes with?

I would like to just have Languages displayed, is that possible?
![spellcheck](https://user-images.githubusercontent.com/163650/66372808-32a51280-e9a7-11e9-8378-77b79054008c.png)

**Comment by wsc-julia-shaptala** [comment]
Duplicated issue is reported here under [#173](https://github.com/WebSpellChecker/ckeditor-plugin-scayt/issues/173).
