### ISSUE TITLE
Content injection happening when viewing source

### ISSUE THREAD

**Issue by epchristi** [WebSpellChecker/ckeditor-plugin-wsc#58]
When clicking on the source plugin, a css file from webspellchecker is injected. Here is a screenshot of the link for wscbundle being added 3 times. (once for each click of the source entry)
![image](https://user-images.githubusercontent.com/16124617/66720541-40013900-edbb-11e9-83b2-981cc0c876b9.png)

OS: Windows/Linux
Browser: Chrome
CKEditor Version: 4.12.1
WSC plugin version: 4.12.1 from download link.

**Comment by wsc-julia-shaptala** [comment]
Hi @epchristi, thank you for reporting the issue. Our technical team confirms that this is a bug and plan to fix it in on of the upcoming releases. ETA: beginning of November.

**Comment by martinstreicher** [comment]
Is there an update on this bug? It is causing lots of issues for me.

**Comment by martinstreicher** [comment]
I also have a related question. Is the editor supposed to embed ANY tags in the code it produces? In other words, when I save the contents of the editor, is it supposed to include ANY links to the `wsc.css` file?

**Comment by wsc-julia-shaptala** [comment]
@martinstreicher @epchristi The release with the fix is planned for tomorrow. As soon as it is live, we will let you know.

**Comment by martinstreicher** [comment]
Thank you @wsc-julia-shaptala -- Can you answer the question I posted above? Is it supposed to embed any reference to wsc.css? Can this be disabled?

**Comment by wsc-julia-shaptala** [comment]
@martinstreicher I'm not sure what you mean here. Could you please clarify?

> I also have a related question. Is the editor supposed to embed ANY tags in the code it produces? In other words, when I save the contents of the editor, is it supposed to include ANY links to the wsc.css file?

**Comment by martinstreicher** [comment]
Sure. In my application I saved some very simple content, "This is a simple test." 

I see this when I look at the HTML saved in the database: 

```
<html>
<head>
	<title></title>
	<link href="https://svc.webspellchecker.net/spellcheck31/lf/scayt3/ckscayt/css/wsc.css" rel="stylesheet" type="text/css" />
</head>
<body aria-readonly="false" data-wsc-instance="true" style="font-family:Arial, Helvetica, sans-serif;font-size: 12px">
<p>This is a simple test.&nbsp;</p>
</body>
</html>
```

Is it intentional to save the `<link href...>` in the `<head>`? Is that a bug? Can it be disabled?

**Comment by martinstreicher** [comment]
I have V4.6.2.

**Comment by wsc-julia-shaptala** [comment]
@martinstreicher Yes, this is intentional and this is not a bug. And this can't be disabled as without it there will be no styles added.

By the way, why do you save all HTML page in the database and not just content that will be changed?

**Comment by martinstreicher** [comment]
@wsc-julia-shaptala Thanks for the reply. Other things consume the text saved in the database, so it is stored in its entirely, ready for use. 

As for styles... Do you mean that the wsc.css file defines styles to display text within the editor and outside the editor? Or just within the editor?

**Comment by jshaptala** [comment]
> As for styles... Do you mean that the wsc.css file defines styles to display text within the editor and outside the editor? Or just within the editor?
@martinstreicher wsc.css file is responsible for adding **red** and **green** underlines to the spelling and grammar problems find within the text in the editor. 

> When clicking on the source plugin, a css file from webspellchecker is injected. Here is a screenshot of the link for wscbundle being added 3 times. (once for each click of the source entry).

@epchristi @martinstreicher the fix for the issue is released today. Please check on your end if everything works properly. Don't forget to clean browser cache to make sure you are using the latest .js file.

**Comment by martinstreicher** [comment]
Thank you. Is the fix only in Version 5?

**Comment by jshaptala** [comment]
v5.5.4.3 is versioning of the WebSpellChecker products. Not CKEditor 4. This is a separate product for which we provide our plugins for spelling and grammar check. The fix covers the core application of SpellCheckAsYouType (SCAYT) plugin for *CKEditor 4*.  There is no need to update the version of plugin.
