### ISSUE TITLE
Add package.json file?

### ISSUE THREAD

**Issue by f1ames** [WebSpellChecker/ckeditor-plugin-wsc#59]
We are currently working on unifying the way external plugins are fetched to [`ckeditor4-presets`](https://github.com/ckeditor/ckeditor4-presets) repository during build process (see ckeditor/ckeditor4-presets#43). Previously, external plugins (ones which are not included in [`ckeditor4`](https://github.com/ckeditor/ckeditor4) repository and needs to be fetched from external repository / package registry / etc) where added as git submodules - that's how it was done for SCAYT and WSC CKEditor 4 plugins.

Since we are adding more plugins (Export to PDF for now, fetched from NPM) and decided to add it as NPM dependency via `package.json`, we would like to unify the process and add SCAYT and WSC plugins the same way. It can be done by just adding GH repostiory path (e.g. `https://github.com/WebSpellChecker/ckeditor-plugin-wsc#release.5.6.4.0`) to our `package.json` file. However, this requires that the source repo also has `package.json` file.

Would it be possible on your side to add `package.json` file to this repository so we can use it via NPM?

Related to https://github.com/WebSpellChecker/ckeditor-plugin-scayt/issues/176.

**Comment by AAbakumov** [comment]
Hi @f1ames. We have already updated our repositories with the enhancements you have requested. You can find it under the 5.7.0.0 tag

https://github.com/WebSpellChecker/ckeditor-plugin-wsc/tree/release.5.7.0.0
