### ISSUE TITLE
Spellchecker not load text when editor is destroyed and recreated.

### ISSUE THREAD

**Issue by gsinha** [WebSpellChecker/ckeditor-plugin-wsc#62]
Hi,
We (eboardsolutions.com) are paid customers of spellchecker plugin for ckeditor 4. We encounter a problem that whenever ckeditor is destroyed and recreated, it does not loads editor data in spellcheck dialog box.

Steps to Reproduce:
1. Goto https://qa.eboardsolutions.com/index.aspx?S=3010.
2. Click on login at top right corner (user name : , password: )
3. In menu, goto Meetings>>Meetings Listing.
4. Click on Meeting Testing 08 Dec 2020 on the meeting listing page.
5. OR simply copy paste this url (https://qa.eboardsolutions.com/SB_Meetings/ViewMeeting.aspx?S=3010&MID=90461), instead of step 3 and 4.
6. In this page you will see two items (Level1 and Level2). Click on Level1.
7. Edit the Item by clicking on pencil icon at the brown bar. After editing you will see ckeditor.
8. Click on check spellings tool in editor. Check spelling dialogbox will appear with data properly loaded.
9. Now move on to next item(Level2) by clicking on it and check the spelling.
10. Please note that spellcheck window will not load data from editor. 
![image_spellcheck](https://user-images.githubusercontent.com/485360/101459520-59215d80-395e-11eb-812a-8fef552a0b35.png)

Name of the function used on this page is : setCKEditor 

Basic code on changing items:
editor.destroy();
CKEDITOR.replace(editorID, ...

**Comment by gsinha** [comment]
Thank you so much for helping. Below were the two magical lines which I was missing.
scayt_autoStartup: true,
grayt_autoStartup: true

**Comment by jshaptala** [comment]
@gsinha, Ok thanks for notifying us about this. Just to clarify `scayt_autoStartup` and `grayt_autoStartup` are options to configure SCAYT (as you type functionality) but not this Spell Check dialog. But we are happy to hear that now the problem is resolved.
