### ISSUE TITLE
Plugin EOL information in README file

### ISSUE THREAD

**Issue by f1ames** [WebSpellChecker/ckeditor-plugin-wsc#65]
As WSC is approaching its EOL, we have added appropriate information in [CKEditor 4 documentation](https://ckeditor.com/docs/ckeditor4/latest/features/spellcheck.html#spell-checking-in-a-dialog-window) and on [WSC page in addons repository](https://ckeditor.com/cke4/addon/wsc).

Do you think it would make sense to also add similar information in the README file in this repository?

**Comment by jshaptala** [comment]
Thanks, added.
